[package]
name = "cherryrgb_service"
description = "Service daemon and UHID driver for Cherry RGB Keyboard"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
cherryrgb = { path = "../cherryrgb" }
anyhow = "1.0"
log = "^0.4.17"
clap = { version = "4.3.1", features = ["derive", "cargo", "wrap_help"] }
ctrlc = { version = "3.2.5", features = ["termination"] }
serde_json = "1.0.96"
rgb = { version = "0.8", features = ["serde"] }
file-mode = "0.1.2"
nix = "0.26.2"
systemd-journal-logger = "1.0.0"

[dependencies.simple_logger]
version = "1.13"
default-features = false
